states = [
        {"timer":""},
        {"object":"logo","time":0,"toggle":"hidden"},

        /*
                Slide 1

        {"object":"slide.background","time":0,"toggle":"hidden"},
        {"object":"#slide1","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide1","time":0,"toggle":"hidden"},
        */

        /*
                Slide 2

        {"object":"#slide2","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide2 .show1","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide2 .show2","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide2 .show3","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide2 .show4","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide2 .show5","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide2 .show6","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide2","time":0,"toggle":"hidden"},
        */

        /*
                Slide 3

        {"object":"#slide3","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide3 .show1","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide3 .show2","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide3","time":0,"toggle":"hidden"},
        */

        /*
                Slide 4

        {"object":"#slide4","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide4 .show1","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide4 .show2","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide4 .show3","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide4 .show4","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide4 .show5","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide4 .show6","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide4 .show7","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide4 .show8","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide4 .show9","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide4 .show10","time":0,"toggle":"hidden"},
        {"pause":""},
        {"object":"#slide4","time":0,"toggle":"hidden"},
        {"object":"slide.background","time":0,"toggle":"hidden"},		
        {"pause":""},
        */

        /* 
         * First Commit
         */
        {"object":".workspace","time":0,"toggle":"hidden"},
        {"object":"tree","time":0,"toggle":"hidden"},
//        {"pause":""},
        //create foo
        {"object":".d-j","time":0,"toggle":"offscreen front center"},
//        {"pause":""},
        {"object":".d-j","time":0,"toggle":"nopip"},
//        {"pause":""},
        {"object":".d-j","time":0,"toggle":"front center position1-5"},
//        {"pause":""},
        //create bar
        {"object":".c-5","time":0,"toggle":"offscreen front center"},
//        {"pause":""},
        {"object":".c-5","time":0,"toggle":"nopip"},
//        {"pause":""},
        {"object":".c-5","time":0,"toggle":"front center position2-5"},
//        {"pause":""},
        //create baz
        {"object":".c-7","time":0,"toggle":"offscreen front center"},
//        {"pause":""},
        {"object":".c-7","time":0,"toggle":"nopip"},
//        {"pause":""},
        {"object":".c-7","time":0,"toggle":"front center position3-4"},
//        {"pause":""},
        //create fiz
        {"object":".line2-4-to-1-5","time":0,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},
        {"object":".s-9","time":0,"toggle":"offscreen front center"},
//        {"pause":""},
        {"object":".s-9","time":0,"toggle":"nopip"},
//        {"pause":""},
        {"object":".s-9","time":0,"toggle":"front center position2-4"},
//        {"pause":""},
        //create settings
        {"object":".line2-3-to-2-4","time":0,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},
        {"object":".h-6","time":0,"toggle":"offscreen front center"},
//        {"pause":""},
        {"object":".h-6","time":0,"toggle":"nopip"},
//        {"pause":""},
        {"object":".h-6","time":0,"toggle":"front center position2-3"},
//        {"pause":""},
        //create app
        {"object":".d-2","time":0,"toggle":"offscreen front center"},
//        {"pause":""},
        {"object":".d-2","time":0,"toggle":"nopip"},
//        {"pause":""},
        {"object":".d-2","time":0,"toggle":"front center position1-3"},
//        {"pause":""},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        //create root
        {"object":"tree","time":0,"toggle":"hidden"},
        {"object":".c-8","time":200,"toggle":"offscreen front center"},
//        {"pause":""},
        {"object":".c-8","time":0,"toggle":"nopip"},
//        {"pause":""},
        {"object":".c-8","time":0,"toggle":"front center position1-2"},
//        {"pause":""},
        //create commit
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".h-q","time":0,"toggle":"offscreen front center"},
//        {"pause":""},
        {"object":".h-q","time":0,"toggle":"nopip"},
//        {"pause":""},
        {"object":".h-q","time":0,"toggle":"front center position1-1"},
//        {"pause":""},
        //create register master
        {"object":".master","time":0,"toggle":"offscreen front center"},
//        {"pause":""},
        {"object":".master .pip","time":0,"toggle":"hidden"},
        {"object":".master .pip","time":500,"toggle":"pip-q-h"},
        {"object":".master .pip","time":200,"toggle":"hidden"},
//        {"pause":""},
        {"object":".master","time":0,"toggle":"front center position4-5"},
//        {"pause":""},
        
        /*
         * make a change
         */
        //change baz
        {"object":".c-7","time":300,"toggle":"position3-4"},
        {"object":".d-5","time":300,"toggle":"offscreen front center"},
//        {"pause":""},
        {"object":".d-5","time":0,"toggle":"nopip"},
//        {"pause":""},
        {"object":".d-5","time":0,"toggle":"front center position3-4"},
        {"object":".ph2-3","time":300,"toggle":"changed"},
        {"object":".ph1-2","time":300,"toggle":"changed"},
        {"object":".ph1-1","time":300,"toggle":"changed"},
//        {"pause":""},
        {"object":".h-6","time":0,"toggle":"position2-3"},
        {"object":".d-q","time":300,"toggle":"offscreen position2-3"},
//        {"pause":""},
        {"object":".d-q","time":0,"toggle":"nopip"},
        {"object":".ph2-3","time":500,"toggle":"changed unchanged"},
//        {"pause":""},
        {"object":".c-8","time":0,"toggle":"position1-2"},
        {"object":".c-9","time":300,"toggle":"offscreen position1-2"},
//        {"pause":""},
        {"object":".c-9","time":0,"toggle":"nopip"},
        {"object":".ph1-2","time":500,"toggle":"changed unchanged"},
//        {"pause":""},
        {"object":".h-q","time":0,"toggle":"position1-1"},
        {"object":".s-4","time":300,"toggle":"offscreen position1-1"},
//        {"pause":""},
        {"object":".s-4","time":0,"toggle":"nopip"},
        {"object":".ph1-1","time":500,"toggle":"changed unchanged"},
//        {"pause":""},
        {"object":".ph1-1","time":0,"toggle":"unchanged"},        
        {"object":".ph1-2","time":0,"toggle":"unchanged"},
        {"object":".ph2-3","time":0,"toggle":"unchanged"},
        {"object":".master .pip","time":0,"toggle":"hidden"},
        {"object":".master .pip","time":500,"toggle":"pip-q-h pip-4-s"},
        {"object":".master .pip","time":200,"toggle":"hidden"},
//        {"pause":""},
        
        {"object":".c-9","time":0,"toggle":"position1-2"},
        {"object":".line1-1-to-1-2","time":25,"toggle":"hidden"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".d-2","time":25,"toggle":"position1-3"},
        {"object":".d-q","time":25,"toggle":"position2-3"},
        {"object":".line2-3-to-2-4","time":25,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},       
        {"object":".s-9","time":25,"toggle":"position2-4"},
        {"object":".d-5","time":25,"toggle":"position3-4"},
        {"object":".line2-4-to-1-5","time":25,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},
        {"object":".d-j","time":25,"toggle":"position1-5"},
        {"object":".c-5","time":25,"toggle":"position2-5"},
        
        {"object":".h-q","time":100,"toggle":"position1-1"},
        {"object":".s-4","time":100,"toggle":"position1-1 position1-2"},
        {"object":".line1-1-to-1-2","time":100,"toggle":"hidden"},
        
//        {"pause":""},
        {"object":".h-q","time":0,"toggle":"hidden"},
        {"object":".s-4","time":0,"toggle":"hidden"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".master","time":0,"toggle":"hidden"},
        {"object":"body","time":0,"toggle":"klee"},
        
        /*
         * Kaylee clones the repo
         */
        
        /* Klee requests the repo */
//        {"pause":""},
        {"object":".h-q","time":0,"toggle":"hidden"},
        {"object":".s-4","time":0,"toggle":"hidden"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".master","time":0,"toggle":"hidden"},
        {"object":"body","time":0,"toggle":"klee"},

        /* Master resolves what needs to be transmitted */
//        {"pause":""},
        {"object":".s-4","time":100,"toggle":"position1-2"},
        {"object":".c-8","time":100,"toggle":"position1-2"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".d-2","time":100,"toggle":"position1-3"},
        {"object":".h-6","time":100,"toggle":"position2-3"},
        {"object":".line2-3-to-2-4","time":100,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},       
        {"object":".s-9","time":100,"toggle":"position2-4"},
        {"object":".c-7","time":100,"toggle":"position3-4"},
        {"object":".line2-4-to-1-5","time":100,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},
        {"object":".d-j","time":100,"toggle":"position1-5"},
        {"object":".c-5","time":100,"toggle":"position2-5"},       

//        {"pause":""},
        {"object":".s-4","time":100,"toggle":"position1-1"},
        {"object":".h-q","time":0,"toggle":"position1-1 position2-1"},
        {"object":".c-9","time":100,"toggle":"position1-2"},
        {"object":".c-8","time":0,"toggle":"position1-2 position2-1"},
        {"object":".d-q","time":100,"toggle":"position2-3"},
        {"object":".h-6","time":0,"toggle":"position2-3 position2-1"},
        {"object":".d-5","time":100,"toggle":"position3-4"},
        {"object":".c-7","time":0,"toggle":"position3-4 position2-1"},

//        {"pause":""},
        {"object":".s-4","time":100,"toggle":"position1-1 position2-1"},
        {"object":".c-9","time":100,"toggle":"position1-2 position2-1"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".d-2","time":100,"toggle":"position1-3 position2-1"},
        {"object":".d-q","time":100,"toggle":"position2-3 position2-1"},
        {"object":".line2-3-to-2-4","time":100,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},       
        {"object":".s-9","time":100,"toggle":"position2-4 position2-1"},
        {"object":".d-5","time":100,"toggle":"position3-4 position2-1"},
        {"object":".line2-4-to-1-5","time":100,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},
        {"object":".d-j","time":100,"toggle":"position1-5 position2-1"},
        {"object":".c-5","time":100,"toggle":"position2-5 position2-1"},

        /* transfer files */
//        {"pause":""},
        {"object":"body","time":0,"toggle":"klee"},
        {"object":".master","time":0,"toggle":"hidden"},

//        {"pause":""},
        {"object":".d-q","time":100,"toggle":"position2-1"},
        {"object":".d-j","time":100,"toggle":"position2-1"},
        {"object":".d-5","time":100,"toggle":"position2-1"},
        {"object":".d-2","time":100,"toggle":"position2-1"},
        {"object":".c-9","time":100,"toggle":"position2-1"},
        {"object":".c-8","time":100,"toggle":"position2-1"},
        {"object":".c-7","time":100,"toggle":"position2-1"},
        {"object":".c-5","time":100,"toggle":"position2-1"},
        {"object":".h-q","time":100,"toggle":"position2-1"},
        {"object":".h-6","time":100,"toggle":"position2-1"},
        {"object":".s-9","time":100,"toggle":"position2-1"},
        {"object":".s-4","time":100,"toggle":"position2-1"},

        /* Create master branch */
//        {"pause":""},
        {"object":".master","time":0,"toggle":"hidden"},

        /*
         * Introduce origin/master
         */
//        {"pause":""},
        {"object":".origin","time":0,"toggle":"nopip offscreen position4-4"},
        
//        {"pause":""},        
        {"object":".origin .pip","time":0,"toggle":"hidden"},
        {"object":".origin .pip","time":500,"toggle":"pip-4-s"},
        {"object":".origin .pip","time":200,"toggle":"hidden"},

//        {"pause":""},
        {"object":"body","time":0,"toggle":"klee"},
        {"object":".origin","time":0,"toggle":"hidden"},

        /*
         * Create a branch
         */

        {"object":".h-q","time":100,"toggle":"position1-1"},
        {"object":".s-4","time":100,"toggle":"position1-2"},
        {"object":".line1-1-to-1-2","time":100,"toggle":"hidden"},

//        {"pause":""},
        {"object":".feature","time":0,"toggle":"nopip offscreen position4-4"},
        
//        {"pause":""},        
        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":500,"toggle":"pip-4-s"},
        {"object":".feature .pip","time":200,"toggle":"hidden"},

//        {"pause":""},        
        {"object":".s-k","time":0,"toggle":"offscreen front center"},

//        {"pause":""},        
        {"object":".s-k","time":0,"toggle":"nopip"},

//        {"pause":""},        
        {"object":".s-k","time":0,"toggle":"front center position1-3"},
        {"object":".line1-2-to-1-3","time":100,"toggle":"hidden"},

//        {"pause":""},        
        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":500,"toggle":"pip-k-s"},
        {"object":".feature .pip","time":200,"toggle":"hidden"},

//        {"pause":""},
        {"object":".h-q","time":100,"toggle":"position1-1"},
        {"object":".s-4","time":100,"toggle":"position1-2"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".s-k","time":100,"toggle":"position1-3"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},

        {"object":".d-6","time":100,"toggle":"offscreen position1-1"},
        {"object":".d-10","time":100,"toggle":"offscreen position1-2"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".d-2","time":100,"toggle":"position1-3"},
        {"object":".s-2","time":100,"toggle":"offscreen position2-3"},
        {"object":".line2-3-to-2-4","time":100,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},       
        {"object":".s-9","time":100,"toggle":"position2-4"},
        {"object":".d-8","time":100,"toggle":"offscreen position3-4"},
        {"object":".line2-4-to-1-5","time":100,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},
        {"object":".d-j","time":100,"toggle":"position1-5"},
        {"object":".c-5","time":100,"toggle":"position2-5"},       

        {"object":".ph3-4","time":300,"toggle":"changed"},
        {"object":".ph2-3","time":300,"toggle":"changed"},
        {"object":".ph1-2","time":300,"toggle":"changed"},
        {"object":".ph1-1","time":300,"toggle":"changed"},

        {"object":".d-8","time":100,"toggle":"nopip"},
        {"object":".ph3-4","time":300,"toggle":"changed unchanged"},
        {"object":".s-2","time":100,"toggle":"nopip"},
        {"object":".ph2-3","time":300,"toggle":"changed unchanged"},
        {"object":".d-10","time":100,"toggle":"nopip"},
        {"object":".ph1-2","time":300,"toggle":"changed unchanged"},
        {"object":".d-6","time":100,"toggle":"nopip"},
        {"object":".ph1-1","time":300,"toggle":"changed unchanged"},
        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":500,"toggle":"pip-k-s pip-6-d"},
        {"object":".feature .pip","time":200,"toggle":"hidden"},

//        {"pause":""},
        {"object":".ph3-4","time":0,"toggle":"unchanged"},
        {"object":".ph2-3","time":0,"toggle":"unchanged"},
        {"object":".ph1-2","time":0,"toggle":"unchanged"},
        {"object":".ph1-1","time":0,"toggle":"unchanged"},
    
        {"object":".d-6","time":100,"toggle":"position1-1"},
        {"object":".d-10","time":100,"toggle":"position1-2"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".d-2","time":100,"toggle":"position1-3"},
        {"object":".s-2","time":100,"toggle":"position2-3"},
        {"object":".line2-3-to-2-4","time":100,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},       
        {"object":".s-9","time":100,"toggle":"position2-4"},
        {"object":".d-8","time":100,"toggle":"position3-4"},
        {"object":".line2-4-to-1-5","time":100,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},
        {"object":".d-j","time":100,"toggle":"position1-5"},
        {"object":".c-5","time":100,"toggle":"position2-5"},       
        
        {"object":".h-q","time":100,"toggle":"position1-1"},
        {"object":".s-4","time":100,"toggle":"position1-2"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".s-k","time":100,"toggle":"position1-3"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".d-6","time":100,"toggle":"position1-4"},
        {"object":".line1-3-to-1-4","time":0,"toggle":"hidden"},

        /*
         * Merge branch into master (fast forward)
         */

//        {"pause":""},
        {"object":".master .pip","time":0,"toggle":"hidden"},
        {"object":".master .pip","time":500,"toggle":"pip-4-s pip-6-d"},
        {"object":".master .pip","time":200,"toggle":"hidden"},

        {"object":".s-k","time":100,"toggle":"position1-3"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".d-6","time":100,"toggle":"position1-4"},
        {"object":".line1-3-to-1-4","time":0,"toggle":"hidden"},
        {"object":"body","time":200,"toggle":"klee"},
        {"object":".master .pip","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".master .pip","time":500,"toggle":"pip-4-s pip-6-d"},
        {"object":".feature .pip","time":0,"toggle":"pip-6-d"},
        {"object":".master .pip","time":200,"toggle":"hidden"},
        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".feature","time":0,"toggle":"hidden"},
        {"object":".origin","time":0,"toggle":"hidden"},

//        {"pause":""},        
        {"object":".s-10","time":300,"toggle":"offscreen front center"},

        {"object":".s-10","time":300,"toggle":"nopip"},

        {"object":".s-10","time":300,"toggle":"front center position1-3"},
        {"object":".line1-2-to-1-3","time":100,"toggle":"hidden"},
        {"object":".feature","time":300,"toggle":"hidden position4-4 position4-3"},
        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":500,"toggle":"pip-4-s pip-10-s"},
        {"object":".feature .pip","time":200,"toggle":"hidden"},
    
//        {"pause":""},
        {"object":".s-q","time":300,"toggle":"offscreen front center"},

        {"object":".s-q","time":300,"toggle":"nopip"},

        {"object":".s-q","time":300,"toggle":"front center position1-4"},
        {"object":".line1-3-to-1-4","time":100,"toggle":"hidden"},
        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":500,"toggle":"pip-10-s pip-q-s"},
        {"object":".feature .pip","time":200,"toggle":"hidden"},


//        {"pause":""},
        {"object":".h-q","time":100,"toggle":"position1-1"},
        {"object":".s-4","time":100,"toggle":"position1-2"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".s-10","time":100,"toggle":"position1-3"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".s-q","time":100,"toggle":"position1-4"},
        {"object":".line1-3-to-1-4","time":0,"toggle":"hidden"},

        {"object":".c-a","time":100,"toggle":"offscreen position1-1"},
        {"object":".s-6","time":100,"toggle":"offscreen position1-2"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".d-2","time":100,"toggle":"position1-3"},
        {"object":".d-9","time":100,"toggle":"offscreen position2-3"},
        {"object":".line2-3-to-2-4","time":100,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},       
        {"object":".h-3","time":100,"toggle":"offscreen position2-4"},
        {"object":".d-5","time":100,"toggle":"position3-4"},
        {"object":".line2-4-to-1-5","time":100,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},
        {"object":".h-10","time":100,"toggle":"offscreen position1-5"},
        {"object":".c-5","time":100,"toggle":"position2-5"},       

//        {"pause":""},
        {"object":".ph1-5","time":300,"toggle":"changed"},
        {"object":".ph2-4","time":300,"toggle":"changed"},
        {"object":".ph2-3","time":300,"toggle":"changed"},
        {"object":".ph1-2","time":300,"toggle":"changed"},
        {"object":".ph1-1","time":300,"toggle":"changed"},

        {"object":".h-10","time":100,"toggle":"nopip"},
        {"object":".ph1-5","time":300,"toggle":"changed unchanged"},
        {"object":".h-3","time":100,"toggle":"nopip"},
        {"object":".ph2-4","time":300,"toggle":"changed unchanged"},
        {"object":".d-9","time":100,"toggle":"nopip"},
        {"object":".ph2-3","time":300,"toggle":"changed unchanged"},
        {"object":".s-6","time":100,"toggle":"nopip"},
        {"object":".ph1-2","time":300,"toggle":"changed unchanged"},
        {"object":".c-a","time":100,"toggle":"nopip"},
        {"object":".ph1-1","time":300,"toggle":"changed unchanged"},
        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":500,"toggle":"pip-q-s pip-a-c"},
        {"object":".feature .pip","time":200,"toggle":"hidden"},

//        {"pause":""},
        {"object":".ph1-5","time":0,"toggle":"unchanged"},
        {"object":".ph2-4","time":0,"toggle":"unchanged"},
        {"object":".ph2-3","time":0,"toggle":"unchanged"},
        {"object":".ph1-2","time":0,"toggle":"unchanged"},
        {"object":".ph1-1","time":0,"toggle":"unchanged"},
        
        {"object":".s-6","time":100,"toggle":"position1-2"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".d-2","time":100,"toggle":"position1-3"},
        {"object":".d-9","time":100,"toggle":"position2-3"},
        {"object":".line2-3-to-2-4","time":100,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},       
        {"object":".h-3","time":100,"toggle":"position2-4"},
        {"object":".d-5","time":100,"toggle":"position3-4"},
        {"object":".line2-4-to-1-5","time":100,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},
        {"object":".h-10","time":100,"toggle":"position1-5"},
        {"object":".c-5","time":100,"toggle":"position2-5"},  

        {"object":".c-a","time":100,"toggle":"position1-1 position1-5"},
        {"object":".h-q","time":100,"toggle":"position1-1"},
        {"object":".s-4","time":100,"toggle":"position1-2"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".s-10","time":100,"toggle":"position1-3"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".s-q","time":100,"toggle":"position1-4"},
        {"object":".line1-3-to-1-4","time":0,"toggle":"hidden"},
        {"object":".line1-4-to-1-5","time":0,"toggle":"hidden"},

//        {"pause":""},
        {"object":".s-k","time":100,"toggle":"position2-3"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".d-6","time":100,"toggle":"position2-4"},
        {"object":".line2-3-to-2-4","time":0,"toggle":"hidden"},
        {"object":".origin .pip","time":0,"toggle":"hidden"},
        {"object":".origin .pip","time":500,"toggle":"pip-4-s pip-6-d"},
        {"object":".origin .pip","time":200,"toggle":"hidden"},

        /*
         * Initiate a 3-way merge
         */
//        {"pause":""},
        {"object":".ph2-4","time":0,"toggle":"unchanged"},    
//        {"pause":""},
        {"object":".ph1-5","time":0,"toggle":"unchanged"},    
//        {"pause":""},
        {"object":".ph1-2","time":0,"toggle":"unchanged"},    

//        {"pause":""},
        {"object":".h-q","time":0,"toggle":"position1-1"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".s-10","time":0,"toggle":"position1-3"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".s-q","time":0,"toggle":"position1-4"},
        {"object":".line1-3-to-1-4","time":0,"toggle":"hidden"},
        {"object":".line1-4-to-1-5","time":0,"toggle":"hidden"},
        {"object":".s-k","time":0,"toggle":"position2-3"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".line2-3-to-2-4","time":0,"toggle":"hidden"},
        
//        {"pause":""},
        {"object":".ph1-2","time":0,"toggle":"unchanged"},    
        {"object":".s-4","time":300,"toggle":"position1-2 position1-1"},
//        {"pause":""},
        {"object":".ph2-4","time":0,"toggle":"unchanged"},    
        {"object":".d-6","time":300,"toggle":"position2-4 position3-5"},
//        {"pause":""},
        {"object":".ph1-5","time":0,"toggle":"unchanged"},    
        {"object":".c-a","time":300,"toggle":"position1-5 position3-5"},

//        {"pause":""},
        {"object":".c-9","time":300,"toggle":"position1-2"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".d-2","time":300,"toggle":"position1-3"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".d-q","time":300,"toggle":"position2-3"},
        {"object":".s-9","time":300,"toggle":"position2-4"},
        {"object":".line2-3-to-2-4","time":100,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},       
        {"object":".d-5","time":300,"toggle":"position3-4"},
        {"object":".d-j","time":300,"toggle":"position1-5"},
        {"object":".c-5","time":300,"toggle":"position2-5"},
        {"object":".line2-4-to-1-5","time":100,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},

//        {"pause":""},
        {"object":".s-4","time":0,"toggle":"position1-1"},
        {"object":".c-a","time":0,"toggle":"position1-1 position3-5"},
        {"object":".ph1-1","time":0,"toggle":"changed"},
        {"object":".c-9","time":300,"toggle":"position1-2"},
        {"object":".s-6","time":0,"toggle":"position1-2"},
        {"object":".ph1-2","time":0,"toggle":"changed"},    
        {"object":".ph1-3","time":0,"toggle":"unchanged"},    
        {"object":".d-q","time":300,"toggle":"position2-3"},
        {"object":".d-9","time":0,"toggle":"position2-3"},
        {"object":".ph2-3","time":0,"toggle":"changed"},    
        {"object":".s-9","time":300,"toggle":"position2-4"},
        {"object":".h-3","time":0,"toggle":"position2-4"},
        {"object":".ph2-4","time":0,"toggle":"changed"},
        {"object":".ph3-4","time":0,"toggle":"unchanged"},    
        {"object":".d-j","time":300,"toggle":"position1-5"},
        {"object":".h-10","time":0,"toggle":"position1-5"},
        {"object":".ph1-5","time":0,"toggle":"changed"},    
        {"object":".ph2-5","time":0,"toggle":"unchanged"},    

//        {"pause":""},
        {"object":".c-a","time":0,"toggle":"position1-1"},
        {"object":".d-6","time":0,"toggle":"position1-1 position3-5"},
        {"object":".ph1-1","time":0,"toggle":"changed conflict"},
        {"object":".s-6","time":300,"toggle":"position1-2"},
        {"object":".d-10","time":0,"toggle":"position1-2"},
        {"object":".ph1-2","time":0,"toggle":"changed conflict"},    
        {"object":".d-9","time":300,"toggle":"position2-3"},
        {"object":".s-2","time":0,"toggle":"position2-3"},
        {"object":".ph2-3","time":0,"toggle":"changed conflict"},
        {"object":".d-5","time":300,"toggle":"position3-4"},
        {"object":".d-8","time":0,"toggle":"position3-4"},
        {"object":".ph3-4","time":0,"toggle":"unchanged changed"},    

//        {"pause":""},
        {"object":".ph1-5","time":0,"toggle":"changed"},
        {"object":".ph2-5","time":0,"toggle":"unchanged"},
        {"object":".ph2-4","time":0,"toggle":"changed"},
        {"object":".ph3-4","time":0,"toggle":"changed"},
        {"object":".ph1-3","time":0,"toggle":"unchanged"},

//        {"pause":""},
        {"object":".s-2","time":0,"toggle":"position2-3"},
        {"object":".d-3","time":0,"toggle":"offscreen position2-3"},
        {"object":".d-3","time":500,"toggle":"nopip"},
        {"object":".ph2-3","time":0,"toggle":"conflict"},

//        {"pause":""},
        {"object":".d-10","time":0,"toggle":"position1-2"},
        {"object":".s-j","time":0,"toggle":"offscreen position1-2"},
        {"object":".s-j","time":500,"toggle":"nopip"},
        {"object":".ph1-2","time":0,"toggle":"conflict"},

//        {"pause":""},
        {"object":".d-6","time":0,"toggle":"position1-1"},
        {"object":".h-j","time":0,"toggle":"offscreen position1-1"},
        {"object":".h-j","time":500,"toggle":"nopip"},
        {"object":".ph1-1","time":0,"toggle":"conflict"},
        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":500,"toggle":"pip-a-c pip-j-h"},
        {"object":".feature .pip","time":200,"toggle":"hidden"},

        {"timer":""},
        {"pause":""},
        {"object":".s-j","time":0,"toggle":"position1-2"},
        {"object":".d-2","time":0,"toggle":"position1-3"},
        {"object":".d-3","time":0,"toggle":"position2-3"},
        {"object":".h-3","time":0,"toggle":"position2-4"},
        {"object":".d-8","time":0,"toggle":"position3-4"},
        {"object":".h-10","time":0,"toggle":"position1-5"},
        {"object":".c-5","time":0,"toggle":"position2-5"},
        
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".line2-3-to-2-4","time":0,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},       
        {"object":".line2-4-to-1-5","time":0,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},

        {"object":".h-j","time":100,"toggle":"position1-1 position2-5"},
        {"object":".s-4","time":100,"toggle":"position1-1"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".s-10","time":100,"toggle":"position1-2"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".s-q","time":100,"toggle":"position1-3"},
        {"object":".c-a","time":100,"toggle":"position1-4"},
        {"object":".line1-3-to-1-4","time":0,"toggle":"hidden"},

        {"object":".s-k","time":100,"toggle":"position2-2"},
        {"object":".line1-1-to-2-2","time":0,"toggle":"hidden"},
        
        {"object":".d-6","time":100,"toggle":"position2-3"},
        {"object":".line2-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".line1-4-to-2-5","time":0,"toggle":"hidden"},
        {"object":".line2-3-to-2-5","time":0,"toggle":"hidden"},

//        {"pause":""},
        {"object":".master .pip","time":0,"toggle":"hidden"},
        {"object":".master .pip","time":500,"toggle":"pip-4-s pip-j-h"},
        {"object":".master .pip","time":200,"toggle":"hidden"},

//        {"pause":""},
        {"object":".origin .pip","time":0,"toggle":"hidden"},
        {"object":".origin .pip","time":500,"toggle":"pip-6-d pip-j-h"},
        {"object":".origin .pip","time":200,"toggle":"hidden"},

//        {"pause":""},
        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".feature","time":0,"toggle":"hidden"},
        {"object":".origin .pip","time":0,"toggle":"hidden"},
        {"object":".origin","time":0,"toggle":"hidden"},
        {"object":"body","time":0,"toggle":"klee"},

        {"object":".h-j","time":0,"toggle":"position2-5"},
        {"object":".s-4","time":0,"toggle":"position1-1"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".s-10","time":0,"toggle":"position1-2"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".s-q","time":0,"toggle":"position1-3"},
        {"object":".c-a","time":0,"toggle":"position1-4"},
        {"object":".line1-3-to-1-4","time":0,"toggle":"hidden"},

        {"object":".s-k","time":0,"toggle":"position2-2"},
        {"object":".line1-1-to-2-2","time":0,"toggle":"hidden"},
        
        {"object":".d-6","time":0,"toggle":"position2-3"},
        {"object":".line2-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".line1-4-to-2-5","time":0,"toggle":"hidden"},
        {"object":".line2-3-to-2-5","time":0,"toggle":"hidden"},

//        {"pause":""},
        {"object":"body","time":0,"toggle":"hoban"},
        {"object":".origin .pip","time":0,"toggle":"hidden"},
        {"object":".origin","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".feature","time":0,"toggle":"hidden"},

        {"object":".h-j","time":300,"toggle":"position1-1"},
        {"object":".s-j","time":300,"toggle":"position1-2"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".d-2","time":300,"toggle":"position1-3"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".d-3","time":300,"toggle":"position2-3"},
        {"object":".h-3","time":300,"toggle":"position2-4"},
        {"object":".line2-3-to-2-4","time":100,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},       
        {"object":".d-8","time":300,"toggle":"position3-4"},
        {"object":".h-10","time":300,"toggle":"position1-5"},
        {"object":".c-5","time":300,"toggle":"position2-5"},
        {"object":".line2-4-to-1-5","time":100,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},

//        {"pause":""},
        {"object":".d-8","time":300,"toggle":"position3-4"},
        {"object":".s-5","time":300,"toggle":"offscreen position3-4"},
        {"object":".s-5","time":500,"toggle":"nopip"},
        {"object":".ph3-4","time":300,"toggle":"changed"},
        {"object":".ph2-3","time":0,"toggle":"changed"},
        {"object":".ph1-2","time":0,"toggle":"changed"},
        {"object":".ph1-1","time":0,"toggle":"changed"},
        {"object":".ph3-4","time":300,"toggle":"changed unchanged"},
        {"object":".d-3","time":300,"toggle":"position2-3"},
        {"object":".d-k","time":300,"toggle":"offscreen position2-3"},
        {"object":".d-k","time":500,"toggle":"nopip"},
        {"object":".ph2-3","time":300,"toggle":"changed unchanged"},
        {"object":".s-j","time":300,"toggle":"position1-2"},
        {"object":".h-9","time":300,"toggle":"offscreen position1-2"},
        {"object":".h-9","time":500,"toggle":"nopip"},
        {"object":".ph1-2","time":300,"toggle":"changed unchanged"},
        {"object":".h-j","time":300,"toggle":"position1-1"},
        {"object":".c-4","time":300,"toggle":"offscreen position1-1"},
        {"object":".c-4","time":500,"toggle":"nopip"},
        {"object":".ph1-1","time":300,"toggle":"changed unchanged"},
        {"object":".ph3-4","time":1000,"toggle":"unchanged"},
        {"object":".ph2-3","time":0,"toggle":"unchanged"},
        {"object":".ph1-2","time":0,"toggle":"unchanged"},
        {"object":".ph1-1","time":0,"toggle":"unchanged"},
        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":500,"toggle":"pip-j-h pip-4-c"},
        {"object":".feature .pip","time":200,"toggle":"hidden"},

//        {"pause":""},
        {"object":".c-4","time":0,"toggle":"position1-1"},
        {"object":".h-9","time":0,"toggle":"position1-2"},
        {"object":".d-2","time":0,"toggle":"position1-3"},
        {"object":".d-k","time":0,"toggle":"position2-3"},
        {"object":".h-3","time":0,"toggle":"position2-4"},
        {"object":".s-5","time":0,"toggle":"position3-4"},
        {"object":".h-10","time":0,"toggle":"position1-5"},
        {"object":".c-5","time":0,"toggle":"position2-5"},

        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".line2-3-to-2-4","time":0,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},       
        {"object":".line2-4-to-1-5","time":0,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},
        
        {"object":"body","time":0,"toggle":"hoban"},
        {"object":".origin","time":0,"toggle":"hidden"},
        {"object":".feature","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":500,"toggle":"pip-4-c pip-j-h"},

//        {"pause":""},
        {"object":"body","time":0,"toggle":"zoe"},
        {"object":".origin","time":0,"toggle":"hidden"},

        {"object":".s-q","time":0,"toggle":"position1-1"},
        {"object":".s-k","time":0,"toggle":"position2-1"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".line2-1-to-2-2","time":0,"toggle":"hidden"},
        {"object":".c-a","time":0,"toggle":"position1-2"},
        {"object":".d-6","time":0,"toggle":"position2-2"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".h-j","time":0,"toggle":"position1-3"},
        {"object":".line2-2-to-1-3","time":0,"toggle":"hidden"},
        
//        {"pause":""},
        {"object":".feature","time":0,"toggle":"hidden"},

//        {"pause":""},
        {"object":".h-a","time":300,"toggle":"offscreen front center"},
        {"object":".h-a","time":300,"toggle":"nopip"},
        {"object":".h-a","time":300,"toggle":"front center position1-4"},
        {"object":".line1-3-to-1-4","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":500,"toggle":"pip-j-h pip-a-h"},
        {"object":".feature .pip","time":200,"toggle":"hidden"},

//        {"pause":""},
        {"object":".s-q","time":0,"toggle":"position1-1"},
        {"object":".s-k","time":0,"toggle":"position2-1"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".line2-1-to-2-2","time":0,"toggle":"hidden"},
        {"object":".c-a","time":0,"toggle":"position1-2"},
        {"object":".d-6","time":0,"toggle":"position2-2"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".h-j","time":0,"toggle":"position1-3"},
        {"object":".line2-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".h-a","time":0,"toggle":"position1-4"},
        {"object":".line1-3-to-1-4","time":0,"toggle":"hidden"},

        {"object":".c-3","time":300,"toggle":"offscreen position1-1"},
        {"object":".d-4","time":300,"toggle":"offscreen position1-2"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".d-2","time":300,"toggle":"position1-3"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".c-6","time":300,"toggle":"offscreen position2-3"},
        {"object":".h-8","time":300,"toggle":"offscreen position2-4"},
        {"object":".line2-3-to-2-4","time":100,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},       
        {"object":".c-j","time":300,"toggle":"offscreen position3-4"},
        {"object":".h-10","time":300,"toggle":"position1-5"},
        {"object":".c-k","time":300,"toggle":"offscreen position2-5"},
        {"object":".line2-4-to-1-5","time":100,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},

        {"object":".c-k","time":300,"toggle":"nopip"},
        {"object":".h-8","time":300,"toggle":"nopip"},
        {"object":".c-j","time":300,"toggle":"nopip"},
        {"object":".c-6","time":300,"toggle":"nopip"},
        {"object":".d-4","time":300,"toggle":"nopip"},
        {"object":".c-3","time":300,"toggle":"nopip"},

        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":500,"toggle":"pip-a-h pip-3-c"},
        {"object":".feature .pip","time":200,"toggle":"hidden"},

//        {"pause":""},
        {"object":".master .pip","time":0,"toggle":"hidden"},
        {"object":".master .pip","time":500,"toggle":"pip-j-h pip-3-c"},
        {"object":".master .pip","time":200,"toggle":"hidden"},

//        {"pause":""},
        {"object":".origin .pip","time":0,"toggle":"hidden"},
        {"object":".origin .pip","time":500,"toggle":"pip-j-h pip-3-c"},
        {"object":".origin .pip","time":200,"toggle":"hidden"},

//        {"pause":""},
        {"object":".c-3","time":0,"toggle":"position1-1"},
        {"object":".d-4","time":0,"toggle":"position1-2"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".d-2","time":0,"toggle":"position1-3"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".c-6","time":0,"toggle":"position2-3"},
        {"object":".h-8","time":0,"toggle":"position2-4"},
        {"object":".line2-3-to-2-4","time":0,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},       
        {"object":".c-j","time":0,"toggle":"position3-4"},
        {"object":".h-10","time":0,"toggle":"position1-5"},
        {"object":".c-k","time":0,"toggle":"position2-5"},
        {"object":".line2-4-to-1-5","time":0,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},
        
        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".master .pip","time":0,"toggle":"hidden"},
        {"object":".origin .pip","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":500,"toggle":"pip-4-c pip-3-c"},
        {"object":".master .pip","time":0,"toggle":"pip-j-h pip-3-c"},
        {"object":".origin .pip","time":0,"toggle":"pip-j-h pip-3-c"},
        {"object":".feature .pip","time":200,"toggle":"hidden"},
        {"object":".master .pip","time":0,"toggle":"hidden"},
        {"object":".origin .pip","time":0,"toggle":"hidden"},

        {"object":"body","time":0,"toggle":"zoe hoban"},

//        {"pause":""},
        {"object":".origin .pip","time":0,"toggle":"hidden"},
        {"object":".origin .pip","time":500,"toggle":"pip-j-h pip-3-c"},
        {"object":".origin .pip","time":200,"toggle":"hidden"},
        
        {"object":".c-a","time":0,"toggle":"position1-1"},
        {"object":".d-6","time":0,"toggle":"position2-1"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".line2-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".h-j","time":0,"toggle":"position1-2"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".h-a","time":0,"toggle":"position1-3"},
        {"object":".line1-3-to-1-4","time":0,"toggle":"hidden"},
        {"object":".c-3","time":0,"toggle":"position1-4"},
        {"object":".c-4","time":0,"toggle":"position2-3"},

//        {"pause":""},
        {"object":".ph1-2","time":0,"toggle":"unchanged"},
        {"object":".ph2-3","time":0,"toggle":"unchanged"},
        {"object":".ph1-4","time":0,"toggle":"unchanged"},

//        {"pause":""},
        {"object":".c-a","time":0,"toggle":"position1-1"},
        {"object":".d-6","time":0,"toggle":"position2-1"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".line2-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".h-a","time":0,"toggle":"position1-3"},
        {"object":".line1-3-to-1-4","time":0,"toggle":"hidden"},
        {"object":".c-3","time":0,"toggle":"position1-4"},
        {"object":".c-4","time":0,"toggle":"position2-3"},
        {"object":".ph1-2","time":0,"toggle":"unchanged"},
        {"object":".ph2-3","time":0,"toggle":"unchanged"},
        {"object":".ph1-4","time":0,"toggle":"unchanged"},

        {"object":".h-j","time":0,"toggle":"position1-2 position1-1"},
        {"object":".s-j","time":300,"toggle":"position1-2"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".d-2","time":300,"toggle":"position1-3"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".d-3","time":300,"toggle":"position2-3"},
        {"object":".h-3","time":300,"toggle":"position2-4"},
        {"object":".line2-3-to-2-4","time":100,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},       
        {"object":".d-8","time":300,"toggle":"position3-4"},
        {"object":".h-10","time":300,"toggle":"position1-5"},
        {"object":".c-5","time":300,"toggle":"position2-5"},
        {"object":".line2-4-to-1-5","time":100,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},


//        {"pause":""},
        {"object":".h-j","time":0,"toggle":"position1-1"},
        {"object":".c-4","time":0,"toggle":"position1-1"},
        {"object":".ph1-1","time":0,"toggle":"changed"},
        {"object":".s-j","time":300,"toggle":"position1-2"},
        {"object":".h-9","time":0,"toggle":"position1-2"},
        {"object":".ph1-2","time":0,"toggle":"changed"},    
        {"object":".ph1-3","time":0,"toggle":"unchanged"},    
        {"object":".d-3","time":300,"toggle":"position2-3"},
        {"object":".d-k","time":0,"toggle":"position2-3"},
        {"object":".ph2-3","time":0,"toggle":"changed"},    
        {"object":".ph2-4","time":0,"toggle":"unchanged"},
        {"object":".d-8","time":300,"toggle":"position3-4"},
        {"object":".s-5","time":0,"toggle":"position3-4"},
        {"object":".ph3-4","time":0,"toggle":"changed"},    
        {"object":".ph1-5","time":0,"toggle":"unchanged"},    
        {"object":".ph2-5","time":0,"toggle":"unchanged"}, 

//        {"pause":""},
        {"object":".c-4","time":0,"toggle":"position1-1"},
        {"object":".c-3","time":0,"toggle":"position1-1"},
        {"object":".ph1-1","time":0,"toggle":"changed conflict"},
        {"object":".h-9","time":300,"toggle":"position1-2"},
        {"object":".d-4","time":0,"toggle":"position1-2"},
        {"object":".ph1-2","time":0,"toggle":"changed conflict"},
        {"object":".d-k","time":300,"toggle":"position2-3"},
        {"object":".c-6","time":0,"toggle":"position2-3"},
        {"object":".ph2-3","time":0,"toggle":"changed conflict"},
        {"object":".h-3","time":300,"toggle":"position2-4"},
        {"object":".h-8","time":0,"toggle":"position2-4"},
        {"object":".ph2-4","time":0,"toggle":"unchanged changed"},
        {"object":".c-j","time":300,"toggle":"position3-4"},
        {"object":".ph3-4","time":0,"toggle":"changed conflict"},
        {"object":".c-5","time":300,"toggle":"position2-5"},
        {"object":".c-k","time":0,"toggle":"position2-5"},
        {"object":".ph2-5","time":0,"toggle":"unchanged changed"}, 

//        {"pause":""},
        {"object":".ph1-3","time":0,"toggle":"unchanged"},
        {"object":".ph1-5","time":0,"toggle":"unchanged"},
        {"object":".ph2-4","time":0,"toggle":"changed"},
        {"object":".ph2-5","time":0,"toggle":"changed"},
        
//        {"pause":""},
        {"object":".c-j","time":0,"toggle":"position3-4 position3-5"},
        {"object":".s-5","time":0,"toggle":"position3-4 position3-3"},

//        {"pause":""},
        {"object":".c-q","time":0,"toggle":"offscreen position3-4"},

//        {"pause":""},
        {"object":".c-q","time":0,"toggle":"nopip"},
        {"object":".c-j","time":0,"toggle":"position3-5"},
        {"object":".s-5","time":0,"toggle":"position3-3"},
        {"object":".ph3-4","time":0,"toggle":"conflict"},

//        {"pause":""},
        {"object":".c-6","time":300,"toggle":"position2-3"},
        {"object":".h-2","time":0,"toggle":"offscreen position2-3"},
        {"object":".ph2-3","time":0,"toggle":"conflict"},
        {"object":".h-2","time":0,"toggle":"nopip"},
        {"object":".d-4","time":300,"toggle":"position1-2"},
        {"object":".h-k","time":0,"toggle":"offscreen position1-2"},
        {"object":".ph1-2","time":0,"toggle":"conflict"},
        {"object":".h-k","time":0,"toggle":"nopip"},
        {"object":".c-3","time":300,"toggle":"position1-1"},
        {"object":".s-8","time":0,"toggle":"offscreen position1-1"},
        {"object":".ph1-1","time":0,"toggle":"conflict"},
        {"object":".s-8","time":0,"toggle":"nopip"},

        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":500,"toggle":"pip-4-c pip-8-s"},
        {"object":".feature .pip","time":200,"toggle":"hidden"},

//        {"pause":""},
        {"object":".s-8","time":0,"toggle":"position1-1 position2-5"},
        {"object":".h-k","time":0,"toggle":"position1-2"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".d-2","time":0,"toggle":"position1-3"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".h-2","time":0,"toggle":"position2-3"},
        {"object":".h-8","time":0,"toggle":"position2-4"},
        {"object":".line2-3-to-2-4","time":0,"toggle":"hidden"},
        {"object":".line2-3-to-3-4","time":0,"toggle":"hidden"},       
        {"object":".c-q","time":0,"toggle":"position3-4"},
        {"object":".h-10","time":0,"toggle":"position1-5"},
        {"object":".c-k","time":0,"toggle":"position2-5"},
        {"object":".line2-4-to-1-5","time":0,"toggle":"hidden"},
        {"object":".line2-4-to-2-5","time":0,"toggle":"hidden"},

        {"object":".c-a","time":0,"toggle":"position1-1"},
        {"object":".d-6","time":0,"toggle":"position2-1"},
        {"object":".line1-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".line2-1-to-1-2","time":0,"toggle":"hidden"},
        {"object":".h-j","time":0,"toggle":"position1-2"},
        {"object":".line1-2-to-1-3","time":0,"toggle":"hidden"},
        {"object":".line1-2-to-2-3","time":0,"toggle":"hidden"},
        {"object":".h-a","time":0,"toggle":"position1-3"},
        {"object":".line1-3-to-1-4","time":0,"toggle":"hidden"},
        {"object":".c-3","time":0,"toggle":"position1-4"},
        {"object":".c-4","time":0,"toggle":"position2-3"},
        {"object":".line2-3-to-2-5","time":0,"toggle":"hidden"},
        {"object":".line1-4-to-2-5","time":0,"toggle":"hidden"},

//        {"pause":""},
        {"object":".feature .pip","time":0,"toggle":"hidden"},
        {"object":".feature .pip","time":500,"toggle":"pip-4-c pip-8-s"},
        {"object":".feature .pip","time":200,"toggle":"hidden"},
        {"pause":""}
]